# Generated by Django 3.1 on 2020-08-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vgsRestApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcardinfo',
            name='card_id',
        ),
        migrations.AlterField(
            model_name='creditcardinfo',
            name='card_number',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='creditcardinfo',
            name='cvv',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='creditcardinfo',
            name='exp_date',
            field=models.CharField(max_length=5),
        ),
    ]
